// TARGET: REPLACE
function scr_brane_error() //gml_Script_scr_brane_error
{
    global.brane_error = 1
    global.cif_destroy = 1
    global.cantsave = true
    scr_stop_music(false, 0)
    scr_stop_ambience(false, 0)
    // instance_create_layer(0, 0, "Instances", obj_brane_error)

    with (obj_sealropes)
        instance_destroy()
    with (obj_collision)
        instance_destroy()
    with (obj_universe)
        instance_destroy()
    with (obj_voidsong)
        instance_destroy()
    with (obj_pit)
        instance_destroy()
    with (obj_floor_tile)
        instance_destroy()
    with (obj_obstacle_parent)
        instance_destroy()
    with (obj_chest_parent)
        instance_destroy()
    with (obj_obsene)
        instance_destroy()
    with (obj_enemy_parent)
        instance_destroy()
    with (obj_enemy_cr_segment)
        instance_destroy()
    with (obj_enemy_cr)
        instance_destroy()
    with (obj_npc_talk)
        instance_destroy()
    with (obj_text_parent)
        instance_destroy()
    with (obj_dustemit)
        instance_destroy()
    with (obj_errormessages)
        depth = 149
    with (obj_voidtail_001)
        instance_destroy()
    with (obj_voidtail_002)
        instance_destroy()
    with (obj_voidtail_003)
        instance_destroy()
    with (obj_voidtail_004)
        instance_destroy()
    with (obj_voidtail_005)
        instance_destroy()
    with (obj_voidtail_006)
        instance_destroy()
    with (obj_voidtail_007)
        instance_destroy()
    with (obj_voidtail_008)
        instance_destroy()
    with (obj_voidtail_009)
        instance_destroy()
    with (obj_voidtail_010)
        instance_destroy()
    with (obj_voidtail_011)
        instance_destroy()
    with (obj_voidtail_012)
        instance_destroy()
    with (obj_voidtail_013)
        instance_destroy()
    with (obj_voidtail_014)
        instance_destroy()
    with (obj_token_uncover)
        instance_destroy()
    with (obj_cc_medal)
        instance_destroy()
    
    // instance_create_layer(x, y, "Instances", obj_orb)
}

